CREATE DATABASE hermesport_db;
USE hermesport_db;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    cep VARCHAR(20) NOT NULL
);

SELECT * FROM usuarios;
DELETE FROM usuarios WHERE id > 0;
SET SQL_SAFE_UPDATES = 0;
